version: "3.9"

services:
  sql-server:
    container_name: hoppyhub-sql-server
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HoppyHub123!
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"

  rabbitmq:
      image: rabbitmq:3-management
      container_name: rabbitmq
      ports:
        - "5672:5672"
        - "15672:15672"
      environment:
        RABBITMQ_DEFAULT_USER: "rabbituser"
        RABBITMQ_DEFAULT_PASS: "rabbituser"

  beer-management:
    container_name: beer-management
    build:
      context: .
      dockerfile: ./Services/BeerManagement/Dockerfile
    env_file:
      - ./Config/.env
    environment:
      - ConnectionStrings__BeerManagementDbConnection=Server=hoppyhub-sql-server;Database=BeerManagement;User=sa;Password=HoppyHub123!;TrustServerCertificate=true
      - TempBeerImageUri=https://hoppyhub.blob.core.windows.net/hoppyhub-container/Beers/temp.jpg
      - ASPNETCORE_URLS=http://*:5000
    ports:
      - "5000:5000"
    depends_on:
      - rabbitmq
      - sql-server

  user-management:
    container_name: user-management
    build:
      context: .
      dockerfile: ./Services/UserManagement/Dockerfile
    env_file:
      - ./Config/.env
    environment:
      - ConnectionStrings__UserManagementDbConnection=Server=hoppyhub-sql-server;Database=UserManagement;User=sa;Password=HoppyHub123!;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://*:5001
    ports:
      - "5001:5001"
    depends_on:
      - rabbitmq
      - sql-server

  favorite-management:
    container_name: favorite-management
    build:
      context: .
      dockerfile: ./Services/FavoriteManagement/Dockerfile
    env_file:
      - ./Config/.env
    environment:
      - ConnectionStrings__FavoriteManagementDbConnection=Server=hoppyhub-sql-server;Database=FavoriteManagement;User=sa;Password=HoppyHub123!;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://*:5002
    ports:
      - "5002:5002"
    depends_on:
      - rabbitmq
      - sql-server

  opinion-management:
    container_name: opinion-management
    build:
      context: .
      dockerfile: ./Services/OpinionManagement/Dockerfile
    env_file:
      - ./Config/.env
    environment:
      - ConnectionStrings__OpinionManagementDbConnection=Server=hoppyhub-sql-server;Database=OpinionManagement;User=sa;Password=HoppyHub123!;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://*:5003
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
      - sql-server

  image-management:
    container_name: image-management
    build:
      context: .
      dockerfile: ./Services/ImageManagement/Dockerfile
    env_file:
      - ./Config/.env
    environment:
      - BlobContainerSettings__BlobConnectionString=${BLOB_CONNECTION_STRING}
      - BlobContainerSettings__BlobContainerName=hoppyhub-container
      - ASPNETCORE_URLS=http://*:5004
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq

  hoppy-hub-app:
    container_name: hoppy-hub-app
    build:
      context: ./Apps/hoppy-hub
      dockerfile: ./Dockerfile
    env_file:
      - ./Config/.env
    ports:
      - "4200:80"
    depends_on:
      - beer-management
      - user-management
      - favorite-management
      - opinion-management
      - image-management