version: '3.8'

services:
  hoppyhubdb:
    container_name: hoppyhubdb
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=HoppyHub123!
      - MSSQL_TCP_PORT=1433
    ports:
      - "1433:1433"
  hoppyhubapi:
    container_name: hoppyhubapi
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - hoppyhubdb
