--The data was generated by AI and may be fake

-- Brewery ids
DECLARE @BrowarStuMostówId NVARCHAR(36) = '9f7fbbcf-75c9-4457-bfef-bf940eb51ccf';
DECLARE @BrowarPintaId NVARCHAR(36) = 'e5631c02-d66a-468c-992f-1bffe9a187ec';
DECLARE @BrowarArtezanId NVARCHAR(36) = 'be8578e1-d5bb-43ca-8ab2-0c625314c078';
DECLARE @BrowarTrzechKumpliId NVARCHAR(36) = 'fdbc7c28-34f9-4963-a17e-176f176bab89';
DECLARE @BrowarNepomucenId NVARCHAR(36) = '57e65f98-51cb-4a60-92e7-db5c80f3a157';
DECLARE @BrowarMaryensztadtId NVARCHAR(36) = '7d9dafe0-4616-4ea7-9540-346093f9cb23';
DECLARE @BrowarZakładowyId NVARCHAR(36) = 'd27c26e4-2e68-42e6-804c-6a190e7d8e9d';
DECLARE @BrowarInneBeczkiId NVARCHAR(36) = 'cb613697-073a-4cad-bc27-8d606b49e5c7';
DECLARE @BrowarProfesjaId NVARCHAR(36) = 'b23f45e1-ca48-41b1-9260-7df386086904';
DECLARE @BrowarSpółdzielczyId NVARCHAR(36) = '155197e5-24f8-4861-8b3e-c6c91247eacf';

-- Breweries
INSERT INTO Breweries
    (Id, Name, Description, FoundationYear, WebsiteUrl)
VALUES (@BrowarStuMostówId, N'Browar Stu Mostów',
        N'Browar Stu Mostów to jedna z najpopularniejszych polskich marek piwnych, słynąca z produkcji kraftowych piw o unikatowym smaku.',
        2015, 'https://www.stumostow.pl/'),
       (@BrowarPintaId, 'Browar Pinta',
        N'Browar Pinta to jedna z najstarszych polskich marek piwnych, słynąca z produkcji piw kraftowych o intensywnym smaku.',
        2011, 'https://www.browarpinta.pl/'),
       (@BrowarArtezanId, 'Browar Artezan',
        N'Browar Artezan to jeden z najbardziej rozpoznawalnych polskich browarów produkujących piwa kraftowe, których receptury są oparte na naturalnych składnikach.',
        2010, 'https://artezan.pl/'),
       (@BrowarTrzechKumpliId, 'Browar Trzech Kumpli',
        N'Browar Trzech Kumpli to producent piw kraftowych, którego celem jest dostarczanie konsumentom unikalnych doznań smakowych.',
        2014, 'https://trzechkumpli.pl/'),
       (@BrowarNepomucenId, 'Browar Nepomucen',
        N'Browar Nepomucen to producent piw kraftowych, który swoją ofertę opiera na naturalnych składnikach i tradycyjnych metodach produkcji.',
        2013, 'https://www.nepomucen.pl/'),
       (@BrowarMaryensztadtId, 'Browar Maryensztadt',
        N'Browar Maryensztadt to producent piw kraftowych, którego filozofia opiera się na szacunku dla tradycji i naturalnych składników.',
        2016, 'https://maryensztadt.pl/'),
       (@BrowarZakładowyId, N'Browar Zakładowy',
        N'Browar Zakładowy to producent piw kraftowych, który swoją ofertę opiera na naturalnych składnikach i tradycyjnych metodach produkcji.',
        2017, 'https://www.browarzakladowy.pl/'),
       (@BrowarInneBeczkiId, 'Browar Inne Beczki',
        N'Browar Inne Beczki to producent piw kraftowych, którego celem jest eksperymentowanie z nowymi smakami i aromatami.',
        2017, 'https://innebeczki.pl/'),
       (@BrowarProfesjaId, 'Browar Profesja',
        N'Browar Profesja to producent piw kraftowych, który swoją ofertę opiera na naturalnych składnikach i wysokim standardzie jakości.',
        2014, 'https://www.profesja.pl/'),
       (@BrowarSpółdzielczyId, N'Browar Spółdzielczy',
        N'Browar Spółdzielczy to producent piw kraftowych, który swoją ofertę opiera na regionalnych recepturach i naturalnych składnikach.',
        2012, 'https://www.browarspoldzielczy.pl/')

-- Addresses
INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), N'ul. Jagiellońska', '75', '30-303', N'Kraków', N'Małopolskie', 'Polska', @BrowarStuMostówId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), 'ul. Jana III Sobieskiego', '78', '62-030', N'Kłodawa', 'Wielkopolskie', 'Polska', @BrowarPintaId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), N'ul. Kościuszki', '123', '32-400', N'Myślenice', N'Małopolskie', 'Polska', @BrowarArtezanId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), N'ul. Powstańców Śląskich', '54', '43-300', N'Bielsko-Biała', N'Śląskie', 'Polska',
        @BrowarTrzechKumpliId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), 'ul. Biskupia', '6', '31-144', N'Kraków', N'Małopolskie', 'Polska', @BrowarNepomucenId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), 'ul. Browarna', '8', '37-310', N'Nowy Sącz', N'Małopolskie', 'Polska', @BrowarMaryensztadtId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), 'ul. Fabryczna', '7', '33-318', 'Gromnik', N'Małopolskie', 'Polska', @BrowarZakładowyId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), 'ul. Krakowska', '12', '25-317', 'Kielce', N'Świętokrzyskie', 'Polska', @BrowarInneBeczkiId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), N'ul. Cieszyńska', '14', '43-100', 'Tychy', N'Śląskie', 'Polska', @BrowarProfesjaId);

INSERT INTO ADDRESSES
    (Id, Street, Number, PostCode, City, State, Country, BreweryId)
VALUES (NEWID(), N'ul. Młyńska', '5', '63-430', N'Luboń', 'Wielkopolskie', 'Polska', @BrowarSpółdzielczyId);