name: Deploy app services

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build-services:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          dotnet-quality: "preview"

      - name: Build UserManagement
        run: dotnet build Services/UserManagement/src/Api/Api.csproj --configuration Release

      - name: Build BeerManagement
        run: dotnet build Services/BeerManagement/src/Api/Api.csproj --configuration Release

      - name: Build OpinionManagement
        run: dotnet build Services/OpinionManagement/src/Api/Api.csproj --configuration Release

      - name: Build FavoriteManagement
        run: dotnet build Services/FavoriteManagement/src/Api/Api.csproj --configuration Release

      - name: Publish UserManagement
        run: dotnet publish Services/UserManagement/src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/UserManagement

      - name: Publish BeerManagement
        run: dotnet publish Services/BeerManagement/src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/BeerManagement

      - name: Publish OpinionManagement
        run: dotnet publish Services/OpinionManagement/src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/OpinionManagement

      - name: Publish FavoriteManagement
        run: dotnet publish Services/FavoriteManagement/src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/FavoriteManagement

  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build-services
    steps:
      - name: Upload UserManagement artifact
        uses: actions/upload-artifact@v4
        with:
          name: UserManagement
          path: /usr/share/dotnet/UserManagement/
          if-no-files-found: error

      - name: Upload BeerManagement artifact
        uses: actions/upload-artifact@v4
        with:
          name: BeerManagement
          path: /usr/share/dotnet/BeerManagement/
          if-no-files-found: error

      - name: Upload OpinionManagement artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpinionManagement
          path: /usr/share/dotnet/OpinionManagement/
          if-no-files-found: error

      - name: Upload FavoriteManagement artifact
        uses: actions/upload-artifact@v4
        with:
          name: FavoriteManagement
          path: /usr/share/dotnet/FavoriteManagement/
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: upload-artifacts
    environment:
      name: "production"

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: UserManagement

      - name: Deploy UserManagement
        id: deploy-user-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hoppy-hub-UserManagement"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_USER_MANAGEMENT_PUBLISH_PROFILE }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: BeerManagement

      - name: Deploy BeerManagement
        id: deploy-beer-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hoppy-hub-BeerManagement"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_BEER_MANAGEMENT_PUBLISH_PROFILE }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: OpinionManagement

      - name: Deploy OpinionManagement
        id: deploy-opinion-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hoppy-hub-OpinionManagement"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_OPINION_MANAGEMENT_PUBLISH_PROFILE }}

      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: FavoriteManagement

      - name: Deploy FavoriteManagement
        id: deploy-favorite-management
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hoppy-hub-FavoriteManagement"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_FAVORITE_MANAGEMENT_PUBLISH_PROFILE }}
