name: .NET 7 CI Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop", "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore dependencies
        run: |
          dotnet restore Common/SharedUtilities/SharedUtilities.sln
          dotnet restore Services/HoppyHub/Hoppy Hub.sln
          dotnet restore Services/UserManagement/UserManagement.sln

      - name: Build solutions
        run:  |
          dotnet build Common/SharedUtilities/SharedUtilities.sln --no-restore
          dotnet build Services/HoppyHub/Hoppy Hub.sln --no-restore
          dotnet build Services/UserManagement/UserManagement.sln --no-restore

      - name: Test solutions
        run: |
          dotnet test Common/SharedUtilities/SharedUtilities.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/HoppyHub/Hoppy Hub.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/UserManagement/UserManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3