name: .NET 8 CI Build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop", "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: |
          dotnet restore Common/SharedUtilities/SharedUtilities.sln
          dotnet restore Services/UserManagement/UserManagement.sln
          dotnet restore Services/BeerManagement/BeerManagement.sln
          dotnet restore Services/ImageManagement/ImageManagement.sln
          dotnet restore Services/FavoriteManagement/FavoriteManagement.sln
          dotnet restore Services/OpinionManagement/OpinionManagement.sln

      - name: Build solutions
        run:  |
          dotnet build Common/SharedUtilities/SharedUtilities.sln --no-restore
          dotnet build Services/UserManagement/UserManagement.sln --no-restore
          dotnet build Services/BeerManagement/BeerManagement.sln --no-restore
          dotnet build Services/ImageManagement/ImageManagement.sln --no-restore
          dotnet build Services/FavoriteManagement/FavoriteManagement.sln --no-restore
          dotnet build Services/OpinionManagement/OpinionManagement.sln --no-restore

      - name: Test solutions
        run: |
          dotnet test Common/SharedUtilities/SharedUtilities.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/UserManagement/UserManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/BeerManagement/BeerManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/ImageManagement/ImageManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/FavoriteManagement/FavoriteManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
          dotnet test Services/OpinionManagement/OpinionManagement.sln --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}