name: UserManagement Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          dotnet-quality: "preview"

      - name: Build with dotnet
        run: dotnet build Services/UserManagement/src/Api/Api.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish Services/UserManagement/src/Api/Api.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "hoppy-hub-UserManagement"
          slot-name: "production"
          package: .
          publish-profile: ${{ secrets.AZURE_USER_MANAGEMENT_PUBLISH_PROFILE }}
